Scarlet-Reach/Scarlet-Reach

code/modules/clothing/rogueclothes/armor.dm
code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm

changes vizier gear to the mix of pontifex/hierophant
yes, it is coal to reuse the assets of other naledi classes, but the other 2 share gear and have unique sprites, whilst vizier gets only a half-mask.
tbh i'd just copy the hierophant's loadout to vizier, but that'd make their looks identical
screenshots!
compared to:
drip
/

vizier clothing changes

---

code/modules/spells/roguetown/acolyte/noc.dm

Currently:
Giant’s Strength
releasedrain: 60
chargedrain: 1
chargetime: 1
Haste
releasedrain: 60
chargedrain: 1
chargetime: 1
invisibility
Releasedrain: 30
chargedrain: 5
chargetime: 5
THis pr changes invisibility to:
invisibility
Releasedrain: 60
chargedrain: 1
chargetime: 5
To be in line with other buffs so you do not instantly get exhausted once the spell is charged. 5 stamina per tick is insane.

Changes invisibility charge costs to be in line with other buffs

---

code/game/objects/items/rogueweapons/melee/special.dm

https://github.com/BlackmoorHold/Blackmoor-hold/pull/157
Scythes/Militiapicks do not use non-combat skills which can be grinded to legendary very easily as their weaponskill.
This is stupid and extremely abusable aswell. Both aren't even bad weapons, infact, they are very good weapons to start with.
Yes, it was already merged aswell.
We shouldn't have hidden powergamer weapons that make no sense.

silly scythe/militiapick nerf (BM PORT)

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
code/modules/spells/roguetown/acolyte/general.dm

Removed bag fixes since im to lazy to learn proper conflict resolving. I'll make the bag fix again if it becomes more of a problem...seems rare anyways.
regression (their healing spell) now always applies the standard healing buff ontop of targeted limb auto healing. This is very similar to the way normal miracles function. I don't believe this was intended originally
Booted up a server and confirmed that even with heavy damage and bleeding on a limb the normal healing buff was applied.
Fixes bug. Bug is bad.

warscholar Vizier fixes

---

code/modules/spells/roguetown/acolyte/pestra.dm

What the title says, basically Pestran's Cure Rot receives a buff but to keep things balanced, I increased the devotion cost and longer cooldown so it can show the efforth a pestra acolyte does to unrot and revive someone if there is lux out of reach or no body knows surgery to extract one.
Priest's Cure Rot is unchaged.
Trust me, it should work.
Because curing rot and not automatically reviving people sucks a lot, specially on lowpop.

Cure Rot miracle spell should revive dead player back regardless of who casts it.

---

code/modules/jobs/job_types/roguetown/church/monk.dm

this returns acolytes to 3 treatment, the main difference is that they can reattach limbs again
numbers change and there's a lot that should get looked at so i skipped testing this
acolytes were originally given 3 treatment from the getgo because its fucking annoying to have to grind up to it roundstart because of how integral it is given how strong chop weapons and WWs are right now - and how annoying it is to have to crawl around to look for someone who can put your leg back on... please dont make this a court phys - aco balance thing, that has to get an intentional look over - this is simply a tedium change

PARITY ROLLBACK - Acolytes get base 3 treatment again

---

code/modules/mob/living/carbon/human/species_types/furry/anthromorph.dm
code/modules/mob/living/carbon/human/species_types/furry/demihuman.dm
code/modules/mob/living/carbon/human/species_types/roguetown/other/halfelf.dm

Simply allows half-elves to better pass as humen if they so wish by giving them the option to unselect ear sprites.
Also does it for tusks on wildkin and halfkin lol whoops almost forgot that part
I was making a half-elf, realized they only get the elf ears and thought the size of them was kind of obnoxious. I thought it'd be a nice way to differentiate them very slightly and allow people to portray different aspects and fractions of elvish blood in their characters while still taking the race, instead of going "ooo, my mother was a half-elf!" '>Corbus is a towering Humen male...'
If preferred I could just sprite a smaller set of elf ears instead so you have to play with SOME kind of visibly point knife-ears instead.
Somebody asked for the other thing and it seemed completely reasonable.

Lets half-elves have humen ears as an option, lets wild-kin and half-kin have tusks

---

code/modules/roguetown/roguecrafting/alchemy/reagents.dm

Makes **Killer's** Ice more deadly, dropping you into crit in mere seconds.
Before.
_Do I really need to screencap the crit screen?_ 
Before Vide ChatGPT code/Azure Peak mass hugboxing, Killer's Ice would instantly crit you in just a few seconds. Currently, it only deals about half your HP. This buffs it back to what it was, an actual **Killer's** poison that crits your victim, it doesn't do worse, no insta kills, but just enough so that you can finish the job quietly.

Buffs Killer's Ice back to what it was

---

_maps/map_files/dun_world/dun_world.dmm

Title! This PR gives the merchant's windows that lead directly inside his shop the same integrity as reinforced windows, while still being transparent.
This simply reinforces the windows so it'll take some more effort to break them, hopefully giving enough time to discourage thiefs from breaking in without a plan, or assholes just throwing rocks through them.
The merchant's windows are there so customers are able to see what wares there are while not having access to them. These, sadly, fail catastrophically the moment someone with a functioning arm obtains a rock. Which meant that if the merchant decided to open their shutters for a moment they were most likely going to get their windows broken and something snatched, or worse, someone jumping inside and closing the shutters to rob the …

Reinforces merchant windows

---

code/modules/events/antagonist/solo/werewolf.dm

What the title says
Tested locally
Parity reverted the initial disabling. We're testing out other antags via admin events panel.

Disables round start werewolfs

---

code/game/objects/items/toys.dm

Changes the suits and names on the Tarot deck to be their modern equivalents.
I replaced some text strings with other text strings of approximately the same length. I forsee no issues.
I, and perhaps others, want to do fortune teller RP and know actual tarot reading. This will make it much easier when the deck uses the names I am used to.

Tarot deck rename

---

code/modules/spells/spell_types/wizard/utility/message.dm
code/modules/spells/spell_types/wizard/utility/mindlink.dm

Mindlink breaks if either person transforms into a Zad or is a zad
Message is made t2 so witches cannot get it
This is because of witches using zad form in combination with these spells to play like a crime reporting drone
As the person who made mindlink this was never it's intended use

Unapologetic salt PR

---

code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm

At present, the Ordinator Inquisitor is a class described as a former Adjudicator (the Templar type of Orthodoxist) promoted up to Inquisitor. However, at present- they get worse armour than their actual Adjudicator underlings. They only get the silver cuirass, which is less coverage than the Adjudicator hauberk (only obtainable through adjudicator spawn.) It seems weird to me that they're running around with shitter armour than their minions, especially given that the cuirass is available for free. This gives the Ordinator Inquisitor ornate half-plate, which can be upgraded through smithing into full plate if they get blessed silver, giving them something to differentiate them as higher ranking.
Ordinator also had a bug from Carl's PR where the shield choice was overriding the satchel …

Gives Ordinator Inquisitor ornate half-plate and fixes satchel bug

---

code/modules/spells/spell_types/wizard/buffs_debuffs/giants_strength.dm

Giant's strength applies strength uncapped for the duration

---

code/controllers/subsystem/timer.dm

PROC_REF(cmp_timer)) -> sortTim(alltimers, /proc/cmp_timer)
one line change what can go bad........................
Dont mind wildkin stuff coz is my fork from main 
an attempt to remove those guys

Cmp timer runtimes fix i hope [Test merge first]

---

code/game/objects/items/rogueweapons/ranged/ammo.dm

There's no sprite named stonearrow, thus stone arrows lacked a sprite, this fixes this.
Bugfix

Appropriately names the stone arrow sprite

---

code/__HELPERS/roundend.dm

rcp was not being added
this was because of the order of the procs cleared the 'nights slept' thing before checking to see if any nights were slept
this just kinda removes the nights slept requirement. being there 45 mins before the round end is already enough for a hotfix
i tested it it worked

Fixes RCP [Hotfix]

---

code/modules/cargo/packsrogue/Sawbones.dm

Removes Killers Ice from sawbones and ups the cost for Emberwine to be at around 100 favour.
With how poisons currently work, I really don't believe that sawbones should be able to buy the most potent poison in the game, nor anyone for that matter. Having someone dip their dagger in killers ice, and then swinging at you procs the poison regardless of if you missed, or failed to pen your opponents armour.
As for Emberwine, sawbones shouldn't be able to buy a drug that decreases most of your stats for a measly 10 favour. 100 is reasonable, considering all the dungeon raiding bandits do these days.

Removal of Killers Ice and Emberwine favour increase for Sawbones

---

code/game/objects/structures/fluff.dm

I noticed a ongoing trend of alarmingly large amounts of lux harvested, Very few lux revivals, minimal bandit interactions or with the town hearing about them or otherwise and bandits doing VERY well in the round end stats. 
With this I have concluded some players are simply not allowed nice things. This removes Lux from the Idol. I'm rather sure but not confirmed outright they have just been farming it. Still something they could do either way and I've never seen a bandit steal lux once in all my time.
Compiles.
Bandits are simply not capable of having nice things. GO **fucking** rob people.

Removes lux from the bandit idol

---

code/__DEFINES/sexcon_defines.dm
code/datums/sexcon/sexcon_helpers.dm
code/modules/surgery/organs/feature_organs/genitals.dm

The idea is to change how the game handles the impregnation proc to be more interactive and cumulative so players can have a bit more interaction with the probabilities to trigger it.
I tested the changes by running a private server on Dream Daemon, granted admin on myself by moving the files from config/example to config and labeling my ckey to the required rank, I instead of using the "roguetest.dm" I waited 5 minutes and ran the standard map as I was still figuring out how this works, managed to get the Server working and spawning myself as a "Male" character stripped it and went back to lobby to respawn as a "Female" both characters with the corresponding organs to properly test it, noticed I forgot to Toggle the ERP Panel Menu, toggled it ON, did the mechanical ERP until I trigger …

Impreg Rework: Add impregnation probability handling to sex actions and genital organs.

---

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/hedgemage.dm

Gives a rogue mage option to wretch mages. -6 spell points for dodge expert, like bandits.
Tested on localhost
Bandit-like mage loadout for wretches since they're both antags

Rogue mage option for wretch mages

---

code/game/objects/items/rogueitems/leash.dm
code/modules/clothing/rogueclothes/neck.dm

This does the following:
-Resolves two confirmed /obj/storage interaction bugs with leashes and several theoretical unconfirmed adjacent bugs. Leashes can no longer be placed into /storage items while attached to someone. Hipslots or hands only.
-Enables leashing on cursed collars. Definitely an oversight. 
-On administrative request, balance tweak to leash interactions. If the victim has combat mode enabled (and is thus resisting as per codebase standard), the leasher takes additional fatigue whilst running. This does not apply if the victim does not have combat mode enabled. 
With victim disabled combat mode:
https://github.com/user-attachments/assets/576611e5-9951-449d-b8bb-a56606a4e4d6
With victim enabled combat mode:
https://github.com/user-attachments/assets/fc070be8-2acf-45b7-8766-c …

Misc Leash Fixes And Balance Tweaks

---

code/modules/roguetown/roguestock/import.dm

Adds horses, direbears, volfs, and something special to the imports list.
Horses are just reskinned saigas without the slight delay on sprinting. Pretty much just a cute prestige mount.
All of the prices have been designed to be fairly high to prevent mass ordering them. If these are too low by any means, let me know. They're meant to be luxury things for fun.
Volfs - 300
Horse - 500
Direbear - 1000
By the way, there's some kind of glitch where injured mounts don't return to their previous speed once fully healed. It's not just horses. No, I don't know how to fix it.
i asked santa for a pony one time and never got over not getting one
Also dukes should be able to make cool volf pits if they want them. And have an attack bear. And have it go terribly wrong.
These aren't all that dangerous …

RETURN OF THE VOLF PIT but not really unless you build it - adds volfs, bears and horses as expensive import items

---

code/modules/mob/living/carbon/carbon.dm

makes it so that throwing. has a delay. and u cant do it again. until the delay is over.
also makes it so that the coin throw admin alert only happens if the stack contains more than 20 coins otherwise it just spams admins 4 no reason.
people shouldnt be able to instantly throw 14 javelins in a row, methinks

Adds Delay To Throwing

---

code/__DEFINES/roguetown.dm
code/game/objects/items/rogueweapons/ranged/ammo.dm
modular_azurepeak/virtues/combat.dm

As it says on the tin. Azure had the bright idea of giving armors piercing values to protect against projectiles but I guess at some point in their process they got balancejakked all wrong, and we wound up with gems such as padded gambesons having 80 piercing protection and the toughest boots having 50. Broadheads were piercing plated boots at 10 perception, let alone at 15. This PR does away with the broadhead arrow AP, giving actual reason to use bodkins, and juices up the piercing protection of a lot of the plate and maille armors. Crossbows are mostly unaffected because they have a whopping 50 AP.
Also caps Toxophilite to Journeyman, same as all other weapon virtues. It's a dumb virtue that just straight up gives you +1 bow skill. It's too much of a no brainer on archer classes and is …

Piercing Armor Buffs, Broadhead AP reduction, Toxophilite capped

---

code/modules/antagonists/roguetown/villain/werewolf/werewolf.dm

With infection code gone they've had to adapt as lone wolves 
Old wolves were definitely on the weaker side imho, their defense/force/AP is really low, this buffs it.
These lonewolves are not ones you should want to 1v1

Buffs werewolf claw

---

modular_azurepeak/code/game/objects/items/ritualcircles.dm

Comments out the devitalized status effect for rite of armaments.
It's a one sentence change.
Neither Zizo or Graggar has this for their version of rite of armaments so this change brings Matthios in line.
Heretics making excitement is always a good thing, rather than doing their rite and hiding for 15 minutes.

Comments out devitalized in matthios rite of armaments

---

_maps/map_files/dun_manor/azure_coast.dmm
_maps/map_files/dun_manor/azure_forest.dmm
_maps/map_files/dun_manor/dun_manor.dmm
_maps/map_files/dun_manor/smalldecap.dmm
_maps/map_files/dun_world/dun_world.dmm
_maps/map_files/rockhill/rockhill.dmm
_maps/map_files/templates/sewers/sewers_topleft_3.dmm

There are a ton of dir overrides for woodentable1, which is not a directional icon. This removes said overrides
I have tested this briefly, but would recommend a testmerge
This is simply a mass replacement of `	dir = 1;\n	icon_state = "tablewood1"` and `	icon_state = "tablewood1";\n	dir = 1` with just 	`icon_state = "tablewood1"`

Remove invalid dir override for some tables

---

code/modules/jobs/job_types/roguetown/church/priest.dm

Trying to use a priest curse on bandits or wretches worshippers will do nothing but still apply the cooldown.
Curses are a tool to punish towner roles ho defy the priest. This shouldn't be used to shut loud, known antags.

Priest's curses do not work on bandits, wretches VL or lich

---

code/__HELPERS/global_lists.dm
code/datums/combat_music.dm
code/modules/admin/topic.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/client/verbs/ooc.dm
code/modules/mob/living/carbon/human/species_types/wildshape/wildshape_transformation.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/mob_helpers.dm
roguetown.dme

With huge thanks to Lukas/leggydog for motivation with this project.
- Allows you to set combat music in preferences (permanent, saves/loads) and from a verb (temporary to mob)
- Adds new `combat_music` singleton datums with metadata for each song. Just define a new one and it'll be added.
- Don't make a datum for a song that's unpopular and otherwise unused. That will just make the RSC larger for no reason.
- Adds a new global list ~~`cmode_tracks_list`~~ `cmode_tracks_by_type` of these singleton datums. Typepath goes in, reference to the instance comes out.
- Persists the override through Verewolf and Wildshape transformations. Transforming copies your override to the new mob. Setting a new track while transformed will also set it for your original mob. The result is seamless …

*READY* COMBAT MUSIC OVERRIDE (Prefs + Options Verb)

---

modular_azurepeak/virtues/utility.dm

This PR removes Ritualist as a virtue you can choose in character creation. It is still available as a trait to every role in the game that started with it previously
This is a really simple change and the virtue is never referenced anywhere else in the code. I can provide testing evidence on request, however
The source of 90% of complaints I have ever heard made about experiences ingame. Ritualist as a trait was never intended to be something everyone had access to, and this is demonstrated through the existence of certain things (hello darksteel/gilded fullplate/kneestinger spam).
Poorly thought out Blackmoor holdovers like this should not exist.

Removes Ritualist Virtue

---

code/modules/mob/typing_indicator.dm

other ppl's typing indicators will show up even if they'reb ehind u.
typing indicator will also show up over everything else, so  if ur pixelshifted under someone it'll still appear

Typing Indicator Shows Up Over Blindspots

---

code/_onclick/hud/plane_master.dm
code/modules/mob/status_procs.dm

Fixes a bug where Baotha's Blessings & Spice would crash you randomly. The root of this might be two issues: 
1. The ripple effect was being called during removal, or was being called twice at the same time.
2. As found by @PPooch in Azure Peak's discord, blur_eyes() might be having some weird interaction.
This PR adds checks to make sure this doesn't happen, and stops these filter conflicts.
<details>
<summary>The issue, before and after</summary>
From PPooch:
https://github.com/user-attachments/assets/2c69c103-2c34-4d05-a4bb-8c3418e3d8cd
Now:
https://github.com/user-attachments/assets/80de0d63-45c1-4e99-98d0-15dfefe2b95e
</details>
bugfixes

Baotha's Bugfixes (Baotha's Blessings & Spice Crash Loop Fix)

---

code/modules/spells/roguetown/acolyte/astrata.dm

Makes anastasis force your spirit back into your body on revive if you ghosted after death but not yet respawned, rather then just cancel revive.
Most revives right now gets failed because players are flying aroung as ghost, waiting for their revive which will never occure because there is check for you to be in your body.
If you dont want to be revived so much then respawn and go into observer again.

Revive while target spirit is not body fix

---

code/game/objects/items/rogueitems/leash.dm

Saw the notif that the main PR got merged and had a small nagging feeling that there's something I overlooked about those procs. Sure enough, there was.
When optimizing the earlier checks that see if they're still nearby and that they belong to the person, I neglected the fact that, after that block, we still don't know for sure if the leash even has an assigned pet. This will runtime for people holding a mix of connected and unconnected leashes at the time they teleport to the other travel tile.
None. Did this on my phone.
Less weird runtimes yippee

Hotfix an oversight from my leash proc that will cause runtimes

---

modular_azurepeak/code/game/objects/items/gwstrap.dm

I usually throw out the greatweapon strap whenever I spawn with it because it takes so long I don't even want to use it outside of combat
this should half it from I think a 5 second delay to 2.5 seconds, making it still very difficult / unworkable in the middle of combat, but not so excruciatingly cheesegrater-tier to use.
halfing the time seems like a good middle point between "people being able to use this in combat" and "people not wanting to use this fucking thing at all".
I don't think anybody likes this thing with how long it takes and it gets thrown away every single time

makes the strap easier to take (from)

---

code/game/turfs/closed/minerals.dm

adds them to the mining pool at a moderate level in med/high rocks, low value at low rocks
yep
it's useful for magic crafts and was otherwise only obtainable via buying it, now it can actually appear in larger quantities 
also hobo mages can get it more reliably now

cinnabar can now be mined

---

code/datums/components/storage/storage_types.dm

Stops mantraps from going inside sacks.
Stops a crime against Ravox from being committed.

Sack Mantrap Fix [HOTFIX]

---

code/_onclick/click.dm

punch misses had practically 0 swing delay so you could just stam yourself out by clicking too much
this uh. makes it missed punches have the same swing delay as successful punches
i punched. i missed.
i punched. i hit.
i picked up a weapon.
i swung. i missed.
i swung. i hit.
it works.
trust.

Fixes Click Delay On Punch Misses

---

code/modules/mob/living/carbon/life.dm

Makes dead nose prevent the "Putrid stinking water!" mood debuff from sewer water.  Simple.
Quick hack-jobbed image. Left is with dead nose, right is without.
Ugly people can now find solace in the sewers, for that is where they belong.

Dead nose prevents sewer water mood loss

---

code/modules/client/preferences.dm
code/modules/mob/living/stats.dm

Changes the stat modifier from being middle aged from: 
-1 Speed +1 Endurance to:
-1 Speed +1 Constitution +1 Fortune (I'm not updating the rest of the PR description, just look at anything86's comment)
This is in an effort to encourage players to make different types of characters without COMPLETELY stunting themselves.  It's still a "net negative" if you consider speed as 2 statpoints like statpacks and racestats do, but it'll be a bit less punishing towards the middle aged users.
It's a one line change bro
I don't expect this PR to work magic, but I'm hoping it helps people feel a bit more free to make characters they enjoy without feeling like they are dropping an anvil on their foot for no trade.

Buffs MILF spawnrate

---

code/modules/mob/living/carbon/human/species_types/roguetown/golem/golem.dm
code/modules/roguetown/roguejobs/engineer/anvil_recipes/mechanical.dm

makes them easier skill-wise to make and install
trust me bro!
anvil recipes are NOT crafting recipes, meaning they can't be easily brute-forced without losing a ton of resources- this wasn't my intention and it resulted in basically locking skill exhibitor creation and installation behind the existence of an artificer (which I _do_ think needs a bit of reason to exist, just not in this way)
Hopefully this allows golem and doll players to actually access the content designed for them to be able to access

golem skill exhibitor tweaks

---

code/modules/roguetown/roguecrafting/items.dm

Makes nooses and gallows craftable (again)
Returns the ability to craft nooses and gallows!
1 rope no skill for noose,
1 rope 2 half logs and novice carpentry for gallows.
I want to fucking hang myself in-game sometimes, this lets me do it without going to one of the very few spots with mapped nooses.

Noose and gallows

---

code/modules/roguetown/roguecrafting/items.dm
code/modules/roguetown/roguecrafting/structure.dm

Craftable noose/gallows PR didn't actually work for the gallows, due to passing the typepath as a string.
Also took the liberty of making nooses craftable if there is no turf above you, which should only happen if you are at the highest point in the overworld or, more importantly, if you're on the Centcomm Z-level.
**This means you can now craft nooses in the Bandit Camp, the Heretic/Wretch Cathedral, and the Vampire Manor.**
Also moves the recipes to their appropriate file where they originally were. 
Things work correctly and good. I don't think people technically being able to craft nooses in the sky will be any real issue.

HOTFIX - Fix crafting gallows, fix crafting nooses on z-level 1

---

code/datums/status_effects/rogue/roguebuff.dm
code/modules/jobs/job_types/roguetown/adventurer/types/wretch/deserter.dm
code/modules/jobs/job_types/roguetown/church/martyr.dm

Buffs now use their own IDs instead of "generic" for adding and removing traits. Prevents them from unintentionally removing traits you spawned in with when their effects wear off.
It's possible that I might have missed some, but this was mainly just me looking over roguebuff.dm while also checking cases where these traits get removed.
For this PR's searchability, this affects:
- Ozium
- Herozium
- Starsugar
- Warden area buff (longstrider)
- Dungeoneer area buff (pugilist)
- Noc darksight ritual
- Necra death bargain ritual
- Dendor lesser wolf rite ritual
- Eora pacifism (pacify) ritual
- Wretch Deserter "brotherhood" or "stand proud" order buff
- Martyr Ultimate Weapon traits ("Vengeance") granted during ult
Compile-tested. There's too many effects for me to try and manually review …

Prevent buffs from removing built-in traits. [Bugfix]

---

code/modules/surgery/organs/eyes.dm

non-goblins will take tox damage and extremely high eye damage, going blind in a few minutes
also fixes the check that was in there because **YOU CAN'T CHECK A SPECIES LIKE THAT!!!!!!!**
also tested with a goblin and it worked fine 
easily-accessible super darkvision for literally anyone who cared to get the eyes implanted massively undermines the value of other sources of darkvision
also pseudo goblin buff maybe since they can use these and still be fine

wild goblin eyes now hurt you while implanted

---

modular/code/modules/living/emote.dm

This PR adds subtle emote targeting.
Upon running a subtle emote string, all visible, conscious mobs within 4 tiles are added to a pickable list, along with choices for all mobs within 1 tile or on the same tile.
For mobs that are hidden/masked/sneaking, they will be ignored however for the 1 tile/same tile choice they will be included in the subtle emote range if close enough.
This allows players to subtle emote within a public setting, and not involve others who would usually object to the emote's content.

Add targeted subtle emoting

---

code/modules/jobs/job_types/roguetown/nobility/steward.dm
code/modules/jobs/job_types/roguetown/yeomen/merchant.dm
modular_azurepeak/code/modules/spells/pantheon/inhumen/matthios.dm

Adds new "spell" for merchant and steward that will calculate total price of a pile of items on a turf
No need to manually calculate price of 5 bags of various items each adventurer dumps infront of you

Pile appraisal skill for merchant and steward

---

code/modules/jobs/job_types/roguetown/youngfolk/apothecary.dm

This PR allows middle-aged people to work at the Apothecary.
TBA (I'm busy)
The only role that allows middle-aged people to be surgeons is Court Phys and Barber Surgeon. Court Phys. is only playable by humans and like maybe 2 other races and Barber Surgeon is a shady back-alley surgeon.

Allow Middle-aged people to be Apothecary

---

code/modules/clothing/rogueclothes/rings.dm

The last dragon ring PR, https://github.com/Scarlet-Reach/Scarlet-Reach/pull/657/ made it so you lose -5 instead of -2 each time you remove the ring, thusly lowering the user's ACTUAL stat by 3 every take it was taken off and if repeated, you can end up with 1 in CON, END and STR. It's bleak milord.
Person who coded the nerf didn't do it right, this fixes it.

Dragon Ring Hotfix

---

code/modules/mob/living/living.dm
modular_azurepeak/virtues/movement.dm

Acrobats lose 50 stamina from landing from a zlevel fall.  This is HOPEFULLY enough to add a cost, but its little enough that an acrobat can drop 2 zlevels in quick succession without stamming out.
It's not nearly as good as having the trait thats literally too good for anybody but werewolves to have removed, but alas.
Now instead of being "entirely" uncatchable, acrobats will only be "mostly" uncatchable upon using their ability to descend 1 zlevel instantly, or 2 zlevels safely.  They'll at least have to wait for their stamina to regen.

Acrobats drain stamina from landing falls

---

code/modules/mob/living/living.dm

Before, all 'resists' (be they putting out fire, or trying to break a grab) had an unreasonable cooldown of two (2) whole seconds in between them. For comparison, a pick intent hit is 1.4 seconds of click delay. This made breaking out of even the most pitiful passive grab a herculean effort in combat and enabled people to disable others by spamming passive grabs.
This PR reduces the CD on grab resisting to 0.8 seconds, the same as a dagger stab (and close to the 1 second of click CD for grabbing), and makes it so whenever you passively grab someone who is actively resisting, they get an automatic, free attempt at breaking the grab. 
In practice this means that grabbing someone in combat will be ineffectual if you don't have the stats or skills to actually properly grab them, and that …

Passive Grab Nerf + Grab Resist CD change

---

code/_onclick/item_attack.dm
code/game/objects/shapeshift_holder.dm
code/game/objects/structures/maneater.dm
code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/species_types/wildshape/wildshape_transformation.dm
code/modules/mob/living/carbon/life.dm
code/modules/mob/living/living_defines.dm
code/modules/spells/roguetown/vampire.dm

it puts them in stasis mode where on_life() doesn't happen, therefore keeping wounds but nullifying oxyloss and bleeding and stuff that would otherwise kill them
cut arm off -> wildshape -> come out of wildshape 10 minutes later -> health and blood is the same -> die from bloodloss 1 minute later because my arm is cut off
it was always a really weird way to handle the person not dying while in wildshape and I have no idea why it was done this way
this brings it slightly more in line with dnd type stuff where your wildshape is basically a shell and your original body retains the damage it took

wildshape (and zad form (and bat form) (and mist form)) no longer fully heals the user

---

code/modules/cargo/packsrogue/Mage.dm

fixes the fact that bandit rogue mage technically had cinnabar ore in their hoard, except that someone typed the path wrong so it didn't really exist. yay!
fixing bugs is awesome and sexy and is known to make your skin smoother

fix cinnabar not appearing in bandit mage hoard

---

code/modules/surgery/bodyparts/bodypart_dismemberment.dm

- Makes decapitations only occur on Strong stance (unless the target has one of two relevant traits).
- Disables dismemberment on hands/feet.
- If not on Strong stance, limb dismemberment is now only a 10% chance after hitting the limb damage threshold (again, negated by crit weakness/easy dismemberment).
Decapitations only occurring on Strong intent is a change that has been discussed before and guarantees that decapitations can only happen with explicit intention behind them. No more accidental decapitations.
Dismembering whole arms and legs by aiming for hands or feet has always been contentious and exacerbates the 'gear check' effect of armor being generally useless if you're not sporting a full competitive set, with at least lightly plated boots.
Finally, dismemberment as a whole is …

Decapitation/Dismemberment Changes

---

modular_stonehedge/code/modules/clothing/rogueclothes/hats.dm

Another part of my crusade against crafting recipes that don't actually tell you what you need to craft them.  This PR also changes the leather padded hood to use skincraft instead of sewing, since it literally only uses leather. It's still a diff of 2 so this changes nothing for anybody except people that stitch shirts to apprentice sewing.
This PR does not touch the items characteristics. Someone else can do that when they lose to someone wearing it.
Tailoring/Skincrafting recipes tell you what they require. This one did not. I fixed the inconsistency.  It was also weird to have an item use sewing instead of skincrafting when leather was the only ingredient.

Leather padded hoods list ingredients

---

modular/code/modules/living/emote.dm

This PR improves #671 by allowing players to target sleeping mobs.
I've tested this and confirm it works.
Allows players to subtle emote even if their partner is sleeping.

Allow subtle emotes to target sleeping mobs

---

code/modules/clothing/rogueclothes/neck.dm

inspired by this tiktok
https://github.com/user-attachments/assets/6095413e-e09f-4809-b1a8-37d14d2d0f21
Lets you wear coifs in the mask slot, this includes leather, chain, and padded coifs.
Layering is fine, thought there might be an issue with the coif going over the neck armor, but it's good.
Less skullcracks, less decaps, more armor for people to spend on which means more work for the smiths.

coif on face

---

code/modules/cargo/packsrogue/merchant/luxury.dm

there's an inexplicable bug i can't figure out that makes it so when you buy a polishing kit sometimes instead of cream and a brush it spits out two creams or two brushes
either way this just makes it so you can buy one or the other which is also useful for getting a refill on cream when you already have a brush
it's a webedit if this breaks the game i'll be shocked
pseudo bug fix and quality of life i don't need a brush when i'm only out of cream

separates polishing cream and polishing brushes in the goldface

---

code/controllers/subsystem/rogue/triumphs/triumph_adjust_procs.dm

Instead of 1 TRIUMPH(S) AWARDED or 2 TRIUMPH(S) AWARDED, it now will do 1 TRIUMPH AWARDED or 2 TRIUMPHS AWARDED.
...look, it bothered me, okay?

Adjust plural from trumph proc.

---

code/game/objects/items/rogueweapons/melee/special.dm

To start out, unarmed weapons have been using a pretty much unique clickcd value instead of a number such as 8 or 10. "CLICK_CD_INTENTCAP" makes it functionally better in every way. (I'm not even joking) 
But drumroll please, for the actual value of what this means! 6, it's fucking 6. 6 is what you would get for using your bare fists. It's faster by 2 than the dagger's 8 which is truly telling with the amount of attacks you can pile up with that extra time while still having a solid 40 pen.
That was just for the Katar, Knuckles are in the same boat while being blunt damage and doing a solid amount of HURTIN', was as fast as a dammed steel dagger while doing a LOT more damage and being 2 slots compact, so they need a little tunin'.
3 line changes it's fine, trust.
Giving unarmed (one of …

Unarmed CD Hotfix

---

code/modules/mob/living/carbon/human/npc/_npc.dm
code/modules/mob/living/living.dm
code/modules/mob/mob_movement.dm

This PR adjusts the spotted while sneaking flavor text for prominent posterior characters.
It also filters out doll species from having their asscheeks clapping while sneaking.

Tweak thicc sneaking spotted text

---

code/game/objects/items/rogueweapons/melee/swords.dm

+ makes iron and steel shortswords swift. Same for the messer (not the kriegmesser) and gladius.
it doth compile
STRchuds never ever use it. The weapon is basically a worse rapier/sabre. Some have even said it deals less dmg than a steel dagger. Having more options for when you lose your rapier/sabre is makes SPD build less miserable.

makes shortsword and *small* messer swift

---

code/modules/jobs/job_types/roguetown/courtier/councillor.dm
code/modules/jobs/job_types/roguetown/courtier/jester.dm
code/modules/jobs/job_types/roguetown/courtier/physician.dm
code/modules/jobs/job_types/roguetown/garrison/dungeoneer.dm
code/modules/jobs/job_types/roguetown/garrison/sergeant.dm
code/modules/jobs/job_types/roguetown/garrison/veteran.dm
code/modules/jobs/job_types/roguetown/nobility/bailiff.dm
code/modules/jobs/job_types/roguetown/nobility/captain.dm
code/modules/jobs/job_types/roguetown/nobility/hand.dm
code/modules/jobs/job_types/roguetown/nobility/knight.dm
code/modules/jobs/job_types/roguetown/nobility/lady.dm
code/modules/jobs/job_types/roguetown/nobility/lord.dm
code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm
code/modules/jobs/job_types/roguetown/youngfolk/prince.dm

Removes the allowed patron: NON_PSYDON_PATRONS from every role it is mentioned in. Keeps the define around in the code just in case.
If the inhumen are (mechanically)allowed to be all of these roles, so should the Psydonites. You can create a guy named "Richter Von Evilstein" have him worship Zizo and queue for duke, yet Psydonites are barred.

Psydonite nobles

---

code/__DEFINES/mobs.dm
code/modules/mob/living/carbon/human/species_types/roguetown/golem/golem.dm

removes limestone golem skin color, added in #648 
way too close to marble which was removed in #624 because it encroached too heavily on dolls in terms of being human-adjacent
all selectable golem colors
same reasoning as in #624, we have steel already and I don't think it fits well lorewise for the distinction between golems and dolls 
there are plenty more interesting character customization options you can have as a golem than just looking like a doll
I'd also debate on looking at copper as well because it's close to dolls' sienna color but I think it looks more orange than anything else

removes limestone from golem colors

---

code/game/atoms_movable.dm
code/modules/mob/dead/observer/observer.dm

throw_at no longer throws infinite move resist mobs e.g observers so you won't get knocked about from random fireballs 
ghosts now properly deorbit when moving instead of spinning around permanently
ghosts now get pixel shifted ~1 tile to the right during orbit so they orbit properly
notice how he's epicsauce orbiting around the mob instead of off to the side
you have absolutely no idea how annoying this shit is to me it's unreal

ghost bugfixes

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/cleric.dm

A simple PR that gives xylix paladins back their amulet and their helmet rather than a generic bucket one. (Why was this changed? I don't know its not even a randomized helmet)

Xylixian cleric AP reverts

---

code/modules/clothing/rogueclothes/armor.dm
code/modules/clothing/rogueclothes/feet.dm
code/modules/clothing/rogueclothes/pants.dm
modular_azurepeak/code/datums/loadout.dm

Adds (hopefully) weak versions of the robes along with the cut-throat pants to the loadout system, the pants typo was fixed.
Three out of the Five just to show for consistency they all have the same weakened state
Further rounds out the loadout for Kazengun items, the robes themselves are severely weakened compared to their actual worthwhile counterparts.

Kazegun Loadout Update

---

code/modules/mob/living/life.dm

This pull request changes the way the PSYDONITE trait works; instead of not healing Psdyonite wounds if they're paralyzed or dead, it inverses that; it will always heal their wounds.
However, if they're already dead, or just really badly injured, it doesn't do anything otherwise to help them. So, your maimed corpse will slowly stop bleeding and its horrifically smashed bones will put themselves back together, but you will not rise without someone there to bring you back.
I found it very evocative of the budding lore for Psydonites to have this ability. In their heresy against the gospel of the Ten, Psydonites believe that the All-Father yet lives and is simply ENDURING in some kind of coma or deep slumber. It would be a grim channeling of Psydon's divinity if his more faithful clerics …

The All Father Lives: Psydonites will always heal wounds, even when dead (although they will not revive without help)

---

code/modules/jobs/job_types/roguetown/nobility/steward.dm
code/modules/jobs/job_types/roguetown/yeomen/merchant.dm

Pulling code from Priestcode and adding to merchant and steward. As of current too many players are grabbing this Virtue and combining it with this trait to circumvent the blacksmith and do things themself. Its powergamey as hell and been requested many times and pulled into question why a noble would get their hands dirty. Also lessens blacksmiths true job.

Blackedsmithy  Disallows Blacksmith Apprentice from Steward and Merchant

---

modular_hearthstone/code/modules/reagents/reagent_containers/lux.dm

plug it into the golem and they get back up, it's that easy
I tested to make sure that lux revival works but I'd prefer if we TM this first just in case I somehow broke something and lux revival doesn't work in some edge case
golems can be revived without astrata worshipers now

adds golem lux revival (TM before merge)

---

code/datums/components/rotting.dm

another attempt to stop golem zombification
waited about 20 minutes with a golem corpse and a human corpse, no zombie or rotting on the golem while the human transformed and started making the fly buzzing noises
golem zombies are really bad because you can't rotcure them without the priest spell
TM first please in case this breaks something else

zombie immune also stops rotting

---

modular_azurepeak/code/modules/jobs/job_types/roguetown/vagabond/failed_apprentice.dm

un-nerfs their base stats, gives them t2 spells instead of t3, also renames the subrole to "failed apprentice" to better reflect both the dm file name and the context of the role
failed apprentice is meant to be talentless and incapable of becoming a proper magos thrall, hence the name- it doesn't really make sense that you can cast all the same spells that proper magos apprentices can cast

reverts AP port failed apprentice changes

---

code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/spells/roguetown/acolyte/noc.dm

makes mobs not detect you if you're under the invis spell's effect
this can sometimes be bypassed by stealth detection stuff (which mire lurkers have) or just attacking / being attacked
if a mob already has you as its target when you cast invis they won't attack you but they will try and shoot ranged attacks at you
[2025-09-12 04-38-28.webm](https://github.com/user-attachments/assets/f41e0056-e5eb-4469-95a8-897926425910)
makes it a higher value pick if you want to avoid getting touched by spiders, keep in mind this can't be used to cheese simplemobs by going invis and whacking them since you drop out of invis if you click anything
this feels kind of shitty and janky but I don't know why it does so I'd appreciate it being TMed so I can fix any unforeseen issues that appear and make it feel …

makes an attempt at making invis useful against simplemobs

---

code/datums/sexcon/sexcon.dm

This PR fixes a bug introduced in #956
It allows grab state to check through clothes, instead of always having the clothes check take priority.
Apparently this was intended behavior, and the bug I fixed was in fact by design - this is now reverted.
Undo a bug fix that was intended by design.

Don't check clothes while checking grab accessibility for sexcon

---

code/modules/spells/roguetown/acolyte/eora.dm

ochre aril (one that makes you explode and die) now drops 2 lux arils as well
also massively increases drop rate of the special arils for the max tier pomegranate
also decreases maximum pruning speed from 25(!!!!!!!!!!!!!!!!!!!!!!!!!) seconds at 0 farming skill to 12 seconds, decreases skill scaling so it's about the same duration when you hit max farming level (previously 4 seconds, now 4.2 seconds)
tested and works as expected
drop rate for lux aril is now ~60% chance per golden pomegranate, up from 6%
imagine this but ~18 seconds x4 each time you harvest a pomegranate and also you need to give it food and water (which also each take time to give to the tree) because the tree's prune/food/water levels reset every time you harvest
considering how much time and effort it costs to bring …

eora pomegranate tree buffs

---

code/modules/spells/roguetown/acolyte/astrata.dm

base damage 10->25
multiplier on undead 2.5 -> 2
it will now deal 50 damage to an undead target, which is a bit less than lightning bolt's 60
cooldown 15s -> 20s
trust me bro!
it's extremely low damage at the moment, this brings it up a bit (but still not nearly as neutrally high-value as most combat spells), especially versus the undead it's intended to be used against

increases sacred flame damage, lengthens cooldown

---

code/modules/jobs/job_types/roguetown/church/templar.dm

Moves the templar scabbard to their left belt slot, so when you pick pestran sickles as a pestran templar you actually get both sickles.
one line change
bugfix

Pestran templar bugfix

---

code/datums/stress/positive_events.dm
code/game/objects/items/rogueitems/inquisitionrelics.dm

title
+40 mood for non-psydons and +2 mood for psydons (they don't get the full bonus because they don't care as much when it activates)
flavor, you should feel good for freeing your buddies from eternal suffering

non inquis get a mood bonus from destroying soul churner

---

code/modules/jobs/job_types/roguetown/adventurer/types/combat/noble.dm

Gives knight errants the option of having a fluted cuirass
Also fixes mentions of Azuria in the descriptions
Gives knight errants a nice equal limb protection loadout option like the other knights
Also no more Azuria

Fluted Cuirass option for knight errants

---

code/__DEFINES/jobs.dm
code/__DEFINES/roguetown.dm
code/modules/jobs/job_types/roguetown/garrison/gatemaster.dm
code/modules/jobs/jobs.dm
roguetown.dme

Brings back the garrison role: gatemaster.  Sit at the gate and open and close it for incoming petitioners to the court and defend it from invaders. 
>
Because in the current state, it is definitely needed for the flow of RP in a round. Especially when most of the roleplay on the server takes place in the court.
> "Yeah but any MAA can do this!"
But they won't.
> "It's a bloat role!"
It is a job that serves it purpose as to what it is described to be. You open and close the gate for the keep.

Garrison Role: Gatemaster

---

modular_azurepeak/virtues/utility.dm

This PR adds a pick pocket virtue called Swift Fingers - it adds the `Pickpocketing` skill to your character.
**Swift Fingers**
_You have a natural talent for weaving your hands into the pockets of others unnoticed, or weightlessly untying a belt. You know how to take away goods from their owners far easier than most travelers._
This Virtue adds the following skills:
**III levels of Pickpocketing, up to Expert**
Makes it easier for players to steal, instead of having to grind up this skill.

Add new Pickpocket virtue Swift Fingers

---

code/__DEFINES/traits.dm

This PR tweaks the language for the dual wielder trait to clear up confusion.
* _If I wield two identical weapons of the same material, I roll twice for my failed attacks. I also roll twice for failed dodges and parries. On attacks that pierce through armor, I roll a 33% chance to strike again at half strength. I do not suffer penalties from using my off-hand in combat._
It's a text change, it'll work fine.
Improves the experience and resolves player frustration with this trait.

Updated dual wielder description to be more verbose/clearer

---

code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm

Essentially a lighter version of https://github.com/Scarlet-Reach/Scarlet-Reach/pull/506.
Ordinator is untouched, as opposed to the former PR. Inquis given a slurbow, a general stat re-spec to make them more a more effective dodge/ranged class, as opposed to just being a worse Ordinator.
A similar PR was already approved, and I was told to work on this by Kite. The last PR was overwritten when the ENDVRE rework came about. At the moment, Inquisitor is just a drippier/worse version of Ordinator. That'd be fine if they had the benefits to make up for it - it isn't a joke/gimmick subclass like inbred - that allow them to be a more traditional dexterous witch-hunter type.

Investigator Inquisitor Buff

---

code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm

Ports part of https://github.com/Rotwood-Vale/Ratwood-2.0/pull/72, which includes:
- Jannisaries **lose the +2SPD and the -1 PER** in exchange for **+2 CON and +1 PER**
- They no longer get a Goedendang start, but rather **axe and shield**. This includes jman axes, leveled up to expert if they pick said start.
- Removed 1 of the 2 starting scabbards, added it to the Shamshir start (so you don't just get two scabbards 4noresin)
Little Lines of Code that were literally ripped out from the PR.
Jannisaries were on the less-picked side, mostly because the rider's main attraction was the two dodge expert classes. I've been checking RW2 out and jannisaries are being picked more often since when their scalemail breaks *(As it always does)*,  they at least have some CON to back up the fact they'll …

Port SOME of the Jannisary changes from RW2

---

_maps/map_files/dun_world/dun_world.dmm
code/datums/magic_items/mages_mechanics.dm/arcana_crafring.dm
code/game/objects/items/rogueitems/gems.dm

This PR makes mana binding collars and gloves more accessable by spawning 2 collars (one in the dungeon master's bedroom and one in the court magicans bedroom drawer) and leaving an extra pair of mana binding gloves at the magos tower
It also renames the debug item "mother of all gems" to "gem" to remove any potential for confusions during crafting
I think this is a good change because it allows for more RP options as a dungeoneer and court magican (punishing apprentices or actually having alive sorcerers as prisoners). It will no longer be required to gag someone and keep them restrained the entire time and allows them to properly engage in roleplay.

Map spawns for mana-binding collars + crafting rename

---

code/datums/character_flaw/_character_flaw.dm
modular_azurepeak/virtues/combat.dm

This basically gives you the negatives of the 'Hollow Lyfe' virtue but without any of the upsides. Silver weakness and miracles burn you. 
Also the trait innately comes with werewolf infection immunity, uuuhhhhhhhhhhh. No good way to disable that. I presume the negatives still outweigh it, but like tell me if you disagree.
Also if you try to game the system by taking Hollow Lyfe and Damned to get a free vice, it gives you Decayed Flesh (no run). 
Tested everything on a localhost. Ran Damned, Hollow Lyfe + Damned, and just Hollow Lyfe. All worked as expected.
Players can roleplay being cursed & evil.

Adds 'Damned' Vice

---

code/modules/mob/living/carbon/human/update_icons.dm

- Fixes an oversight that caused certain items to generate an extra aux arm sprite that covered their sleeves when the character was facing EAST/WEST. This is due to the aux limb being intended to show the hand poking out of sleeves, but items that had inherited a "sleevestate" from a parent, but had their "sleeved" variable set to null were not handled correctly.
- This will have the side-effect of causing said items to appear to have sleeves that cannot be torn off and used for cloth (although the dismemberment mask will still remove them if someone loses an arm). I think this is a worthwhile tradeoff.
It makes things looker more betterer.

fixes sleeves not appearing sometimes

---

code/game/objects/items/rogueitems/necro_relics.dm

Port of: https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/3952
> Necromancers now set a task for their Skeletons, before summoning. This is to give the potential Skeleton player a hint as to what their round might be like.
Unfortunately, not every Skeleton wants to be turned into a Mining Machine for an hour and a half.
> skeletons won't be hot-dropping into an unknown battlefield. They'll at least get a sense of who they're working for, and what they'll be doing. This helps them invested, and might intrigue other players who might never play a skeleton.

Task-based Necromancy (small necromancer QOL change) 

---

code/modules/spells/spell_types/wizard/utility/mending.dm

Fixes an error where the mending spell is given an invalid target organ when healing constructs such as golems and dolls.
This error caused a runtime any time mending was used on a living target, and prevented the correct behavior of the mending spell.
I fixxa da bug

Construct healing fix

---

modular_azurepeak/code/game/objects/items/surgery_bag.dm

Adds the examination hammer to all other surgery bags. This means crafted surgery bags and towner physicians will have one in their bag now. Currently there are two varieties. 
It's a one line change QoL feature, and it helps figure out what is wrong with people for those who do not have the diagnose spell. The main difference between this and the ones apothecaries/court physician get is the pestra needle now... and that's it.
I found it odd that towner physicians wouldn't have a hammer in their bag. Also, it was annoying trying to become an aspiring physician after grinding up treatment and ordering a bag, only to not have something to examine people with (other than your eyes and lots of wasted time) as you lacked the spell to do so. You still take a few seconds to figure it out as …

Examination Hammer Added to Surgery Bags

---

code/modules/clothing/masks/_masks.dm

Makes masks vertical by default, not horizontal.
2 number swaps, if this fucks up we've got bigger problems.
I'm super fucking special in the head and I will go insane, look at the sprite and tell me it should be horizontal without lying through your teeth.

Tiny, Super Small, OCD Fix.
