Scarlet-Reach/Scarlet-Reach

code/modules/mob/living/carbon/human/species_types/roguetown/roguetown_species.dm
=> fixes the valley accent

code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
Gives inquisitor a silver psycross to interrogate with
Tested on localhost
This server fucking SUCKS!
=> Gives inquisitor a psycross

code/modules/spells/roguetown/acolyte/astrata.dm, code/modules/spells/roguetown/acolyte/general.dm
https://github.com/Gehenna-Host/Scarlet-Reach/pull/9
Proof of testing:
=> Bug fix for commit #9 - Properly stops excommunicated healing

code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
This one:
https://github.com/BlackmoorHold/Blackmoor-hold/pull/204/files
=> Resubmit of the daring twit PR

code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
So they're more like a direct upgrade
It's good for the game because we need more people playing inquisition to enforce the lore of the game
=> Brutes now get a choice of weapon like barbs

code/modules/client/preferences.dm
Nixes the dimension limits on that "other" headshot. It is so stupid, and there is no point in having it anyways, unlike the normal headshots.
Without this PR I am fucking *wide*. With this PR I am actually quite normal.
I don't have to make sure everything's cropped to these specific dimensions which is utterly aggravating. OOC Extra does not suffer this at all and things still look fine with that.
=> Removes dimension limits on "alternate" "headshot"

code/datums/migrants/migrant_waves/slaver roles.dm
these heretical foreigners do not care for our customs
also please play zybantyians they're awesome
=> Zybantyians can be any race

code/datums/gods/patrons/inhumen_pantheon.dm
i would kill people for fun but i would never ever (EVER) take away their liberties
=> deazurefies Graggar

code/modules/jobs/job_types/roguetown/garrison/squire.dm
basically makes squires races like azure
removed two lines and it let me select nonrespected races as squire in game :) see code
character freedom & more squires who are weird. knight hasn't been touched so you can just say that non-respected race squires just aren't allowed to become knights
=> squire race expansion ?

.gitignore, config/example/config.txt
Makes it so people can actually join beyond 100 players living.
This is fundamentally impossible for me to test. And I am only 80% confident this works. Still, I consider this very important.
The 20 extra people shouldn't lag the server much more, since most of the lag is codebase related overhead.
=> raises living pop cap to 150

code/modules/cargo/packsrogue/merchant/merchant_potions.dm, code/modules/roguetown/roguecrafting/alchemy.dm, code/modules/roguetown/roguecrafting/alchemy/alch_cauldron_recipes.dm, code/modules/roguetown/roguecrafting/alchemy/alch_items.dm, code/modules/roguetown/roguecrafting/alchemy/reagents.dm
Turns the drinker into a deadite
=> Zizo poison

code/modules/antagonists/roguetown/villain/werewolf/werewolf_transformation.dm
=> Werewolves get swimming

code/game/objects/items/rogueweapons/melee/polearms.dm
What if we made the staff good:
=> Staff of the shepard has cast time reduction and applies firestacks 

code/modules/cargo/packsrogue/merchant/merchant_potions.dm, code/modules/roguetown/roguecrafting/alchemy.dm, code/modules/roguetown/roguecrafting/alchemy/alch_cauldron_recipes.dm, code/modules/roguetown/roguecrafting/alchemy/alch_items.dm, code/modules/roguetown/roguecrafting/alchemy/reagents.dm
Reverts Scarlet-Reach/Scarlet-Reach#203
Requested by @ConstantineII
=> Revert "Zizo poison"

code/modules/antagonists/roguetown/villain/vampire.dm
Was supposed to give them this in the recent PR but forgot
=> Blood loss immune for vampire wretches

code/game/objects/items/rogueitems/undies.dm
adds weight and grid size to underwear so they don't take up an abysmal amount of storage anymore
also adds the same throw speed as zigs and stuff so you can throw your shitstained underwear further
i can finally start a panties collection
=> Underwear grid storage size fix

code/modules/cargo/packsrogue/Brigand.dm, code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm, roguetown.dme
You used to not spawn with anything. Now you do. Yay!
i also tested the brigand iron shield buy. that works.
=> Fixes iron shield and iron sword for Battlemaster

code/modules/clothing/rogueclothes/hats.dm
Title 
Unless they are meant to be steel, otherwise... yeah.
Bugfix
=> Fixes ornate barbute/armet's not smelting silver ore

code/game/objects/structures/apiary.dm
There's no honey_X sprites in honey.dmi, so this will have to do until someone sprites more honey sprites.
Bugfix
=> Fixes medicinal honey + all other variants lacking a sprite

code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
it's drippy and we already do this for the psydontemplars
=> Disciples get faith specific cloaks

code/modules/clothing/rogueclothes/mask.dm, code/modules/mob/living/carbon/carbon.dm
Reverts Scarlet-Reach/Scarlet-Reach#187
=> Revert "Mouthgrabs now take coverage into account, in line with strangling"

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/poacher.dm
+ Gives poacher sewing 1 and medicine 1.
+ Removes stealing 2.
+ Buffs butchering to lvl2.
+ Purely convenience. I know I'm getting the sewing skill EVENTUALLY to repair my starting armour, I just have to stand there and keep going at it for a few minutes.
+ Medicine 1, on the other hand, makes sense for a 'survivalist' creacher to be able to do. However, from a balancing point that skill would, PERHAPS, at some point save a player (captured garrison, themselves or their heretic buddy) from bleeding out to death. Beyond that, wardens already have medicine 1 roundstart.
+ Stealing 2 is lowkey useless and doesn't go along with the whole vibe of the class?
=> poacher wretch balancejak

code/modules/mob/living/emote.dm
Lets people with the guarded virtue faith salute
Tested on localhost
"Sorry, I don't look strong enough to salute my faith."
=> Guarded faith salute

_maps/map_files/dun_world/dun_world.dmm
This PR fixes faulty varedits and removes redundant ones from the map
i code a da serber
=> fixes bad varedits & re-tgms map

code/modules/clothing/rogueclothes/mask.dm, code/modules/mob/living/carbon/carbon.dm
Reverts Scarlet-Reach/Scarlet-Reach#436
=> Revert "Revert "Mouthgrabs now take coverage into account, in line with strangling""

code/datums/wounds/types/fractures.dm, code/game/objects/items/rogueweapons/intents/mmb/bite.dm
disfigurement goes away when ur nose is fixed
dude trust me
=> Fixes Nose Disfigurement

code/__HELPERS/filters.dm, code/_onclick/hud/plane_master.dm, code/datums/status_effects/rogue/roguebuff.dm, code/game/atoms.dm
Cleans up the Baotha's Blessings ( & Spice ) code, despite my null checks there was a very slim chance that filters was creating an empty list, then calling for the length of that empty list and subtracting 1 (or at least that's the running theory)
If this does in fact fix it, big thanks to @grungussuss for the help.
I ported some of Vanderlin's filter-handling methods to help with it.
Color filter works, ripple effect fires and animates, blur_eyes works fine
https://github.com/user-attachments/assets/5b83a079-4be9-4fee-80ce-408e5edcd0ac
mbbbuggg fixessss
=> Baotha's Bugfixes Part II

code/_onclick/hud/screen_objects.dm, code/_onclick/item_attack.dm, code/modules/mob/living/carbon/carbon_defense.dm, code/modules/mob/living/carbon/human/species.dm
limb targetting is highlighted better in attakc messages
and theres an animation showing you which of your limbs are hurt, blocked or grabbed. colour coded, too
https://github.com/user-attachments/assets/bb98c29a-4cce-44f6-8f3e-54fac8c94a4d
look up
=> Better Attack Targetting Feedback

code/datums/particle_weathers/_base.dm, strings/axian_replacement.json
have noticed runtimes 
Dont mind controller coz its because roundstart
=> Runtimes fix 4 [TM first]

code/modules/mob/living/carbon/human/species.dm
lets them wear cloaks too
2 line changes it's fine trust
i wanna wear a cloak. so do others,
=> lets lunabracers wear cloaks

modular_azurepeak/code/datums/loadout.dm
updates and fixes some loadout tabards
uses the new fancy-sprited ones and not the knight ones from oldcode. also allows abbysors to be selected b/c it was merged with necra's
=> Abyssor buff

code/modules/jobs/job_types/roguetown/garrison/manorguard.dm
women get studded leather armor as the MAA archer
TBA
Women get the fuckass bikini rn and it's dumb
=> women get normal armor

strings/accent_universal.json
Adds in 
Sir = Ser | 
Lifestyle = Lyfestyle | 
Tweaks werewolfs to werewolves
The PR that tried to change Ser from Sir made a good point, if we're going to use Ser, might as well make it completely.
_I also used the word lifestyle and it didn't change to lyfe so I'm upset._
=> Updates to the common accent

code/modules/mob/living/carbon/human/species_types/roguetown/golem/golem.dm
gives them zombie immunity trait, forgot about this one because I assumed they couldn't be infected by them already
got bitten by a zombie a lot and didn't get infected
doesn't make sense for them to be infected cuz they have nothing to infect
=> gives golems deadite immunity trait

strings/polish_replacement.json
Polishes it. removes a few translations that didn't work right and fixes a typo and everything
i tested this
the two removed ones were kinda awkward and fired even without appended with a question mark... it's polished now. polish.
=> Polishes Lupian Accent

code/game/objects/items/rogueweapons/intents/mmb/bite.dm, code/modules/mob/living/carbon/life.dm, code/modules/mob/living/life.dm
Removes anything in wounds to prevent permanent runtime loop because the game says ''i cannot fix this shit'' x1000000000
https://github.com/user-attachments/assets/4b6a61a8-ba95-43b3-8537-5690c444d4f0
no more 10000 runtimes for free i guess
=> 5 runtime fix Life () and Wounds () + bite [TM first for a weel]

code/game/objects/items/rogueitems/keyrings.dm, code/modules/jobs/job_types/roguetown/garrison/squire.dm
ultimate PR reposter
- all squires get an iron dagger
- all squires get a copper hammer
- footman squire gets 3 shields
- lancer squire gets a great weapon strap
Lancer gets their stuff
Footman too
and the irregular
Squires are expected to repair equipment, yet there's only one hammer in the entire keep, so they all get crappy stone ones.
Squires get an iron dagger for standardization, so every squire starts with a primary(bow/sword/spear) and a backup(the dagger).
Footman Squires have access to shields, yet not the skill to use them.
=> squire buuuuff 2.0

code/modules/surgery/bodyparts/helpers.dm
Ports half of this PR, https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/3453, since the other half was ported by someone else, this one optimizes missing_limbs
See Original PR.
Reducing cost of procs helps with lag.
=> Optimization Port

code/modules/mob/living/emote.dm
Adds emote button that kills you
Dying and loosing is fun
Its part of story and being grabbed-chained-middle mouse clicked or get red from retarded heal bot good boy yap yap *wag tail boy is not a thing that i want 
Let people die in tf2 style 
UPD: its called set name = "Pray for suicide" now
=> Team Fortess 2 [Роскомнадзор] verb

code/modules/mob/living/carbon/human/life.dm
this includes rain and being in water with your head uncovered
Trust me bro! Forgot to take a screenshot
I want to larp my lamia as being pleased when she gets rained on and seeing the mood debuff despite worshiping the god of the ocean made me really angry in real life and smash my keyboard in frustration
=> abyssor worshipers no longer get sad when headsoaked

code/_onclick/hud/plane_master.dm
Third round of trying to get Baotha's Bugfixes to not crash people's games. This time it's testing time. 
As I cannot consistently replicate the issue in my machine, I pray to get this testmerged for at least a round so I can see if it's the ripple effect that's causing issues, or if it's something else involving druqks
For Round 1 I just commented out the ripple effects.
https://github.com/user-attachments/assets/a771a1eb-914a-4100-9605-5cbc4086d449
bao bao
=> [TM Only] Baotha's Bugfixes III: Third Time's The Charm

code/modules/admin/verbs/adminhelp.dm
https://github.com/tgstation/tgstation/pull/49276
Makes the initial ahelp input multiline.
Makes complaining to admemes easier and more legible rather than being stuffed in one tiny box.
=> Multiline ahelp

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/berserker.dm
gives berserker a +1 to endurance
it's a value change if it makes the game explode that'd be fucking awesome
it was not the same stats as atgervi shaman which were buffed slightly statwise in #367 
comparing it to all the rest of the master unarmed classes it's pretty mediocre
- infinitely summonable katar dodge expert, miracles shaman
- 3str 3con 3end disciple. the only benefit is that it's +1speed rather than -1, but general consensus says grabs are broken so
- 3str 2con 2end 2speed templar w/ unique, better variants of unarmed weapons, alongside having miracles.
i'll give it some more love later but this should be a small little thing for now
=> berserker small lil +1

_maps/map_files/dun_world/dun_world.dmm
Resubmittal of https://github.com/Scarlet-Reach/Scarlet-Reach/pull/717
=> Mapping changes

code/modules/admin/verbs/adminhelp.dm
https://github.com/tgstation/tgstation/pull/59882
Adds a list of other tickets generated by a player when admins look in the ticket.
Useful information for admins to know when the same guy makes multiple ahelps going "I KNOW WHAT YOU DID"
=> 'Other tickets by user'

code/modules/roguetown/roguemachine/scomm.dm
fixes a bug introduced in #666 porting spatial grid
Please properly test all changes in your PRs next time, doubly so when this could have been easily avoided by keeping it testmerged for longer 
it's unironically really aggravating that this issue even existed to begin with
Type 1 in chat if you like archivist players
=> fixes loudmouth horn

code/_onclick/hud/screen_objects.dm, code/datums/sexcon/sexcon.dm, code/modules/mob/living/carbon/human/species.dm
remembering a triumph reloads your balls now too
I am a coom tyrant.
=> Remembering Triumphs Recharges Your Orgasm

code/modules/jobs/job_types/roguetown/yeomen/archivist.dm, code/modules/roguetown/roguemachine/scomm.dm, modular_azurepeak/code/modules/clothing/rogueclothes/crown.dm
makes it so crown does not get duplicated when sumoned anymore
=> Fixes Crown Duplication

code/modules/roguetown/roguemachine/scomm.dm
scoms will shake when called by jabberline, once more
scoms receiving a call will say such also
dude trust me
=> Fixes Jabberline Shake Animation

_maps/map_files/dun_world/dun_world.dmm
Currently, the bathhouse has a fermenting barrel in the kitchen, but you have to go outside to get water. That sucks. I made the barrel a water barrel instead.
=> Bathhouse Kitchen Water

code/modules/surgery/organs/eyes.dm
>>>red eye icon
>>surgery to put them in
>white
flavor
=> wild goblin eyes are now red rather than white

code/modules/reagents/reagent_containers/glass.dm
west is saved
* re-enables milking people, amount milked scales with boob size
* authorizes drone strike on azurean code monkey house who cut this one out from the game
=> returns milking

code/modules/reagents/reagent_containers/glass.dm
we got milking and then we broke drinking
you could not indulge in the fruits of your wife's body
terrible
this fixes that
i drank my own milk. trust me.
y hghhg
=> Fixes Drinking

code/datums/special_traits/traits/traits.dm, code/game/objects/items/beartraps.dm, code/modules/admin/verbs/schizohelp.dm, code/modules/clothing/rogueclothes/hats.dm, modular_azurepeak/code/game/objects/items/ritualcircles.dm, strings/accent_universal.json
nimrod doesn't mean dumb ok
didn't test but it compiles
=> de-nimrodification of code

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/lunacyembracer.dm
doesn't make sense they get T3 miracles but no skill
edited with webeditor so surely nothing explodes for no raisin
trust me bro!
idk
consistency I guess?
=> gives lunacy embracer journeyman holy skill

code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_foreign.dm, code/modules/roguetown/roguecrafting/sewing.dm
makes mentor hat craftable
makes the foreigner katana buyable
yeah it worked.
don't you want foreigner stuff.
=> foreigner katana to merchants, mentor hat craftable.

code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/witch.dm
title
they have ritualist but #743 didn't give them chalk because witch hut spawns with chalk in it
=> gives witch ritual chalk back

code/modules/cargo/packsrogue/merchant/weapons/merch_weapons_foreign.dm
its in the name
simple addition, shouldnt need testing
more variety or something
=> adds shurikens to foreign merchant import

code/modules/mob/living/carbon/human/species_types/furry/lamia.dm, code/modules/surgery/bodyparts/_bodyparts.dm, code/modules/surgery/bodyparts/bodypart_dismemberment.dm, code/modules/surgery/bodyparts/helpers.dm, modular_azurepeak/code/game/objects/items/ritualcircles.dm
the issue was bodyparts not properly updating when delimbed so there was never an owner set
necra's vow now works as intended
lamias now get their tails back when full_healed in any way, also respects their tail color
you now gain / lose lamia tail or legs respectively when your species is changed via VV, non-lamia will just get white tails like you get when selecting the species in game preferences
reattaching limb properly with necra's vow active
bugfixes #584 amongst other issues that have plagued lamia for a bit
=> misc bodypart fixes / necra's vow

code/modules/roguetown/roguecrafting/alchemy/alch_grind_recipes.dm
it gives bonemeal (less than tailbone grind does)
works as expected
allows people to get bonemeal from bones, which I think makes sense
tailbone already exists but it has its own uses and isn't as plentiful so it's not really that enticing to grind up
also you can just get bonemeal from fish infinitely without any combat so it's not really a matter of bonemeal being difficult to access
=> adds normal bone as a grinding recipe

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/berserker.dm
Reverts Scarlet-Reach/Scarlet-Reach#645
It's one of the best if not the best Wretch class in the game, it doesn't need anymore buffs, especially in stats that matter, like endurance.
=> Revert "berserker small lil +1"

code/modules/mob/living/carbon/human/species_types/furry/dracon.dm, code/modules/mob/living/carbon/human/species_types/furry/kobold.dm, code/modules/mob/living/carbon/human/species_types/furry/moth.dm, code/modules/mob/living/carbon/human/species_types/furry/vulpkanin.dm, code/modules/mob/living/carbon/human/species_types/roguetown/golem/doll.dm
gives guys that have 2 sentences of lore some more stuff and adjusted doll flavor text a bit
it compiles and is properly formatted in game
2 sentences of lore is kind of lame
I don't play any of these races so let me know if you don't like this stuff I just put together
=> misc species lore changes

_maps/map_files/dun_world/dun_world.dmm
removes it from the north of the map as i dont like it there, makes the so only one mana fountain exists and its in the swamp
WE LOVE BOG WE LOVE SWAMP WOOOOOO
(i put the file in wrong folder last time)
People said mana fountain in north is bad for the game, this changes that therefore its good for the game.
=> Removes mana fountain from north.

code/modules/mob/living/carbon/human/emote.dm
https://github.com/user-attachments/assets/088f06f3-f4fa-4a15-a41e-195e599a8f9e
=> fixes tailwagging LOL

code/modules/clothing/rogueclothes/armor.dm
A quick patch for PR #953, I forgot to properly add the word light to the pathing for the floral robes
Because, I'm stupid and overlooked a small thing when wrapping up the pr
=> Kazegun Loadout Update : Patch

code/game/objects/items/rogueweapons/melee/knives.dm, code/game/objects/items/rogueweapons/melee/swords.dm, code/modules/clothing/rogueclothes/neck.dm, code/modules/jobs/job_types/roguetown/adventurer/types/wretch/heretic.dm, code/modules/jobs/job_types/roguetown/mercenaries/classes/desertrider.dm
+ fixed zybek loadout
+ desert rider medal is equippable in ring slot
+ reduced delay on pulling in/out knives/swords in your satchel from 10/15 to 2
+ added whip to wretch heretic SPD subclass loadout option
=> raneshi merc fix + whip to loadout of wretch heretic

_maps/map_files/dun_world/dun_world.dmm
It literally just adds 3 spiders to the bog.
I moved some spiders earlier in the bog to other parts of the bog but the werent enough spiders so this added 3.
=> Adds 3 spiders

code/_onclick/drag_drop.dm, code/controllers/subsystem/processing/mousecharge.dm
…
Multiplies charging progress by subsystem tick delta.
I cannot test this in a sim environment due to not being able to replicate lag under load.
spellcasting feels BADDDDDD sometimes.
=> [TM PLS] makes charge timer account for ticklag to make it feel less inconsistent.

code/modules/clothing/rogueclothes/npc/goblin.dm, code/modules/mob/living/carbon/human/npc/goblin.dm
Fix goblins not being able to spawn with their unique armors.
This will make fighting goblins a bit more challenging, especially for inexperienced players. I haven't touched any of its stats but it shouldn't be a massive buff for them.
=> Goblin armor fix

code/game/objects/structures/traveltile.dm, code/game/turfs/closed/minerals.dm, code/modules/jobs/job_types/roguetown/adventurer/types/wretch/hedgemage.dm, code/modules/mob/living/simple_animal/hostile/retaliate/summons/elemental/_base.dm, code/modules/mob/living/simple_animal/simple_animal.dm, modular_azurepeak/code/datums/loadout.dm
elementals can now mine rock walls
hedge mages now start with guide to magic
you can now get crafting books in loadouts
works as expected
gives elemental summons more flavor, especially crawlers since you can bind them early and they can be a mining buddy
other stuff was on request, not sure if there are balance ramifications to allowing people to have a recipe book in their loadout but it does take up a loadout slot
=> misc magic changes

code/datums/components/storage/storage_types.dm, code/modules/jobs/job_types/roguetown/youngfolk/mage_apprentice.dm, code/modules/mob/living/simple_animal/hostile/retaliate/summons/infernal/imp.dm
=> bugfixes imp summon tier and makes summoner pouches hold all magic items

code/modules/reagents/reagent_containers/glass.dm
no longer gives a message if the target can't lactate or has no breasts 
also provides arousal when milking someone with erp panel enabled
also makes the milk.ogg sound when you do
works as expected, notice the pink tint around the screen
no more "x's chest must be exposed before I can milk them!" after you accidentally target your male dwarf with the wrong drink intent
=> rehandles milking code

code/modules/clothing/rogueclothes/hats.dm
Fixes the lack of eye coverage on the captains helmet
bugfix
=> Captain helmet fix

code/datums/components/slippery.dm, code/datums/components/wet_floor.dm, code/modules/spells/spell_types/wizard/invoked_aoe/slick_trick.dm
now you can jump over the slick trick thing
also fixes duration mistakes by adding a define
makes sense that you cant slip midair
=> Slick Trick fixes so you can jump over it

code/_onclick/hud/mouseover.dm
This PR is port of AP's fix https://github.com/GeneralPantsuIsBadAtCoding/Azure-Peak/pull/3954
https://github.com/user-attachments/assets/a7635ae3-6647-4231-acd8-df34b01a1fb6
Fixes a bug that breaks viewport.
=> Forces maptext to stay within 1,1 bounds (AP port)

code/datums/components/decals/blood.dm
• Replaces expensive mid-game resource access and icon operations in obj/initialize with pregeneration at init and a cache
• Used a non-firing subsystem to handle everything on its own code thread and made the code cleaner and easier to read
• Also fixed the weird .json file that had CRLF end formatting for some reason?
• It Just Works™
• Less lag is more gooder
=> In-hand Icon Cache

code/modules/roguetown/roguemachine/vendor.dm
items of the same type and same name will now stack in peddlers
peddlers will also announce their stock randomly
also fixes keyrings so that they'rll actually lock/unlock the peddler properly
this is for a bounty
why are YOU good for the game?
=> Vendor Item Stacking

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/lunacyembracer.dm
Restricts harpies from being able to be lunacy embracers
<details> <summary> As anything else </summary>
</details>
<details> <summary> As a harpy </summary>
</details>
Fuuuuuuuuuuuck that
=> Harpies cannot be lunacy embracers

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/outlaw.dm
gives light step to the wretch outlaw
wretches should be better than rogues, who have light step
=> fixes an oversight

code/modules/jobs/job_types/roguetown/adventurer/types/wretch/outlaw.dm
small lil outlaw fix, makes maradeurs just a shield option work, the naming was wrong so it didnt give you anything
its a one line change trust me vro
bugfix
=> calm luh outlaw fix

code/modules/jobs/job_types/roguetown/courtier/jester.dm
makes all skills the jesters get random with a few skills having a minimal level, also gives them wrestling and unarmed with a maximum roll of 5 (master)
it works, trvst
its funny
=> makes picking jester a trve gamble, like xylix intended
